Rclapps/clean and cycle
SecureCoLLC/loge pull request #4
Opened 2024-09-24 15:11 UTC by RockClapps

Adds the ability to cycle to new log files when old ones exceed a certain file size. Also deletes old log files when disk is running out of free space. Compiles for linux, windows, and darwin. Tested to work on linux, will follow up after testing on a windows machine. Can't currently test on macOS but it shouldn't be an issue either

2024-09-24 15:55 UTC, RockClapps commented
Just tested and it works on windows as well

2024-09-27 15:50 UTC, spectorl requested changes
Few things I think we may need to clean up here.

2024-09-27 15:50 UTC, spectorl commented on file.go
> +			if err1 != nil || err2 != nil {
Sort order would be unstable in this case. It's an edge case, but I think what you want to do is this:

```
if err1 != nil && err2 != nil {
    return false;
} else if err1 != nil {
    return false;
} else if err2 != nil {
    return true;
}
```

2024-09-27 15:50 UTC, spectorl commented on storageReader_linux.go
> +}
Are the Linux and Darwin implementations identical? If so, we can probably condense.

2024-09-27 15:50 UTC, spectorl commented on storageReader_darwin.go
> +package loge
Does this need a `//go:build darwin` at top?

2024-09-27 15:50 UTC, spectorl commented on storageReader_linux.go
> +package loge
Does this need a `//go:build linux` at top?

2024-09-27 15:50 UTC, spectorl commented on storageReader_windows.go
> +package loge
Does this need a `//go:build windows` at top?

2024-10-02 19:44 UTC, spectorl approved these changes
Looks good to me.

2024-10-02 19:44 UTC, merged